### ISSUE TITLE
Question about history

### ISSUE THREAD

**Issue by paulvi** [joshtronic/php-holidayapi#1]
Is this repository continuation of `https://github.com/joshtronic/holidayapi.com.git` ?

Former README

```
# Holiday API

Holiday API is website (and soon to be stand-alone PHP class) for obtaining
information about holidays. The project was started as a personal challenge to
see if I could generate holiday lists on the fly for any date instead of
keeping a static list in a database.

## Local Development

To install `composer`:

```shell
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
```

To install the dependencies:

```shell
composer install
npm install
```

To install `gulp`:

```shell
npm install -g gulp
```

To run the server:

```shell
gulp server
```

```

**Comment by joshtronic** [comment]
Definitely a continuation of the service itself, but not the open source platform offering.

After many years of maintaining the service I came to realize that /most/ of the contributed holiday data was regularly incorrect and maintaining the service was taking up more and more of my time. I pivoted to being a premium service (for which this wrapper is still intended for) to allow me to bootstrap and really punch the gas on the internal development efforts.

Since then the platform has grown from <20 countries to over 160, started to deep dive into country sub-divisions, added international language support and greatly improved accuracy a ton by way of our internal testing and monitoring system.
